name: Delete Branch on Close PR
on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: delete branch
        uses: zjutszl/my-cool-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
