name: Linter

on: [pull_request]

jobs:
  check:
    name: Check Code & Lint Code Base
    runs-on: ubuntu-latest
    steps:
      # Checkout Code Base
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_INCLUDE: .*src/.*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
